### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/project-lab#12]
I've made modifications to the acknowledgements section of the frontmatter.md file. We should go through the different samples during code review and see if we can regularize this a bit, but also add links to the versions run by other fellows.

**Comment by lmrhody** [comment]
We also need to acknowledge our funder!!!

**Comment by kallewesterling** [comment]
I am moving all of this conversation into issue **#17 Create a meta.md file** for now. Feel free to reopen if you want to, @lmrhody.
