### ISSUE TITLE
Set up template for individual lessons

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/project-lab#19]
[This applies to all of the repos]

We need to set up a template for individual lessons, which will be copied as many times into a `lessons` directory as there needs to be lessons in each workshop.

A **lesson**, as we had discussed previously, is centered around a term or a concept.

I have done some starting exploratory work of existing workshop `section` directories to see what the backend would need to look like (i.e. which "data types" exist already, and what a database table would look like on the backend). In that exploratory work, I have made notes of a few things that may be helpful for us in instructions/templates for the fellows' work during sprint 2. See [issue #29 in `django-app`](/DHRI-Curriculum/django-app/issues/29)

**Comment by kallewesterling** [comment]
After our meeting yesterday, @lmrhody, I started working on a backend model for lessons. I think that this is entirely enough work for the fellows for sprint 2, together with a review of what they did for sprint 1. How do you feel @lmrhody and @szweibel?

See: https://github.com/DHRI-Curriculum/django-app/commit/2c5947a5595b5070f6476bb933d111a921728302 (just learned that it is possible to refer to commits in other repositories, btw!)

---

Here are the essential components of a **Lesson** object:

- **title** [str]: short text, max 200 characters, that describes the lesson
- **text** [str]: long text, contains the bulk of the markdown for the lesson
- **order** [int]: defines in which order the lesson comes in the workshop
- (auto-generated) **workshop** [FK]: relationship to a workshop
- (auto-generated) ** challenges** [FK]: relationship to one/more challenges
- (auto-generated) **screenshots** [FK]: relationship to one/more screenshots
- (auto-generated) **created** = models.DateTimeField(auto_now_add=True)
- (auto-generated) **updated** = models.DateTimeField(auto_now=True)

In the commit, you can also see that I have included the ability to create **Challenge** objects:

- **title** [str]: short text, max 200 characters, that describes the challenge
- **text** [str]: long text, contains the bulk of the markdown for the challenge
- (auto-generated) **solution** [FK]: relationship to one/more solutions
- (auto-generated) **screenshots** [FK]: relationship to one/more screenshots

That means that there will also be an ability to create **Solution** objects:

- **title** [str]: short text, max 200 characters, that describes the challenge
- **text** [str]: long text, contains the bulk of the markdown for the challenge
- (auto-generated) **screenshots** [FK]: relationship to one/more screenshots

### Code snippets

Any code snippets can be included in the `text` fields above (on `Lesson`, `Challenge`, or `Solution`), using the three backticks on a single line (` ``` `) to indicate start or end of the code section, and, if possible, also the language (see the Template example below).

---

## Template Example

I imagine that a corresponding template (for each lesson) would look something like this:

```

# 1. Title [the number maps to `Lesson.order` and the text to `Lesson.title`]

Write all the text for the lesson here.

` ` `python
print("Write any python code here, for example.")
` ` `

The code blocks can be inside of the text block

[this whole section maps to `Lesson.text`]

## Challenge (optional): Title for challenge [maps to Challenge.title]

Text for a challenge. [maps to Challenge.text]

### Solution [maps to Solution.title]

Text for a solution. [maps to Challenge.text]

```

**Comment by szweibel** [comment]
Yes, absolutely enough work for sprint 2. This looks good!

**Comment by kallewesterling** [comment]
Thank you @szweibel !
